services:
  flask-app:
    build:
      context: .
    ports:
      - "5001:5001"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: mydatabase
      DB_USER: myuser
      DB_PASSWORD: mypassword
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
  
  postgres:
    image: postgres:latest
    container_name: gospodiprosti
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "15432:5432"
    volumes:
      - postgres-data:/var/lib/postgres/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s

volumes:
  postgres-data: